-- MySQL Script generated by MySQL Workbench
-- Tue 02 Oct 2018 17:02:57 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(256) NOT NULL DEFAULT '',
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(128) NOT NULL DEFAULT '',
  `lname` VARCHAR(256) NOT NULL DEFAULT '',
  `email` VARCHAR(256) NOT NULL DEFAULT '',
  `mobile` VARCHAR(20) NULL DEFAULT '+31 (0) 6 ',
  `roles_id` INT(11) UNSIGNED NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rememberMeToken` VARCHAR(255) NOT NULL,
  `forgotPasswordToken` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `roles_id`),
  INDEX `fk_users_roles_idx` (`roles_id` ASC) ,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`profiles_kids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profiles_kids` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profiles_kids` (
  `id` INT(11) NOT NULL,
  `nickname` VARCHAR(256) NULL DEFAULT NULL,
  `dateofbirth` DATE NOT NULL DEFAULT '2000-01-31' COMMENT 'YYYY-MM-DD',
  `reason` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`profiles_doctors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profiles_doctors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profiles_doctors` (
  `id` INT(11) NOT NULL,
  `nickname` VARCHAR(256) NULL DEFAULT NULL,
  `dateofbirth` DATE NOT NULL DEFAULT '2000-01-31' COMMENT 'YYYY-MM-DD',
  `proficiency` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`profiles_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profiles_owners` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profiles_owners` (
  `id` INT(11) NOT NULL,
  `nickname` VARCHAR(256) NULL DEFAULT NULL,
  `dateofbirth` DATE NOT NULL DEFAULT '2000-01-31' COMMENT 'YYYY-MM-DD',
  `picture` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `mydb`.`profiles` (
  `users_id` INT(11) UNSIGNED NOT NULL,
  `profiles_kids_id` INT(11) NOT NULL,
  `profiles_doctors_id` INT(11) NOT NULL,
  `profiles_owners_id` INT(11) NOT NULL,
  PRIMARY KEY (`profiles_kids_id`, `profiles_doctors_id`, `profiles_owners_id`, `users_id`),
  INDEX `fk_profiles_profiles_kids1_idx` (`profiles_kids_id` ASC) ,
  INDEX `fk_profiles_profiles_doctors1_idx` (`profiles_doctors_id` ASC) ,
  INDEX `fk_profiles_profiles_owners1_idx` (`profiles_owners_id` ASC) ,
  INDEX `fk_profiles_users` (`users_id` ASC) ,
  CONSTRAINT `fk_profiles_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_profiles_kids1`
    FOREIGN KEY (`profiles_kids_id`)
    REFERENCES `mydb`.`profiles_kids` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_profiles_doctors1`
    FOREIGN KEY (`profiles_doctors_id`)
    REFERENCES `mydb`.`profiles_doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_profiles_owners1`
    FOREIGN KEY (`profiles_owners_id`)
    REFERENCES `mydb`.`profiles_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`careforschemas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`careforschemas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`careforschemas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `schema` BLOB NULL DEFAULT NULL,
  `date_start` DATE NULL DEFAULT '2000-01-31' COMMENT 'YYYY-MM-DD',
  `date_review` DATE NULL DEFAULT '2000-01-31' COMMENT 'YYYY-MM-DD',
  `extra` VARCHAR(1024) NULL DEFAULT NULL,
  `profiles_doctors_id` INT(11) NOT NULL,
  `profiles_owners_id` INT(11) NOT NULL,
  `profiles_kids_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `profiles_doctors_id`, `profiles_owners_id`, `profiles_kids_id`),
  INDEX `fk_careforschemas_profiles_doctors1_idx` (`profiles_doctors_id` ASC) ,
  INDEX `fk_careforschemas_profiles_owners1_idx` (`profiles_owners_id` ASC) ,
  INDEX `fk_careforschemas_profiles_kids1_idx` (`profiles_kids_id` ASC) ,
  CONSTRAINT `fk_careforschemas_profiles_doctors1`
    FOREIGN KEY (`profiles_doctors_id`)
    REFERENCES `mydb`.`profiles_doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_careforschemas_profiles_owners1`
    FOREIGN KEY (`profiles_owners_id`)
    REFERENCES `mydb`.`profiles_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_careforschemas_profiles_kids1`
    FOREIGN KEY (`profiles_kids_id`)
    REFERENCES `mydb`.`profiles_kids` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_event` DATE NULL DEFAULT '2000-01-31' COMMENT 'YYYY-MM-DD',
  `eventname` VARCHAR(128) NOT NULL DEFAULT '',
  `pictures` VARCHAR(256) NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(256) NULL DEFAULT NULL,
  `votes` INT(11) NULL DEFAULT '0',
  `events_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `events_id`),
  INDEX `fk_comments_events1_idx` (`events_id` ASC) ,
  CONSTRAINT `fk_comments_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `mydb`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`day2dayinformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`day2dayinformation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`day2dayinformation` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT '2000-01-31' COMMENT 'YYYY-MM-DD',
  `description` VARCHAR(256) NULL DEFAULT '',
  `action` VARCHAR(256) NOT NULL DEFAULT '',
  `profiles_owners_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `profiles_owners_id`),
  INDEX `fk_day2dayinformation_profiles_owners1_idx` (`profiles_owners_id` ASC) ,
  CONSTRAINT `fk_day2dayinformation_profiles_owners1`
    FOREIGN KEY (`profiles_owners_id`)
    REFERENCES `mydb`.`profiles_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
